[package]
name = "fractal-image-comp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
image = "0.25.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
derive_more = { version = "0.99.17" }